### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by amitaibu** [pusher/pusher-angular#11]
After `npm install` and setting the keys, the example doesn't work.

Also I think this is calling non existing files

```
  <link href="/css/style.css" rel="stylesheet">
  <script src="/components/angular/angular.min.js"></script>
  <script src="/components/ui-router/release/angular-ui-router.min.js"></script>
  <script src="//js.pusher.com/2.2/pusher.min.js"></script>
  <script src="/components/pusher-angular/lib/pusher-angular.js"></script>
```

![pusher_collaboration](https://cloud.githubusercontent.com/assets/125707/8092115/57df4b76-0fc0-11e5-9da2-c91424ee5645.jpg)

**Comment by hamchapman** [comment]
Sorry about that - I had the components directory setup in the gitignore file. The components directory is now on master inside the example directory.

Let me know if it's now working for you
