### ISSUE TITLE
Broken bind/unbind logic

### ISSUE THREAD

**Issue by Disparity** [pusher/pusher-angular#15]
When binds, the original callback wraps decorator, which is then used to listen to the events.
When unbind, the user passes the original callback, not the decorator, and unbind not happens.

**Comment by hamchapman** [comment]
I'll take a look into this today - do you have some example code that shows it because as far as I can tell, the tests suggest that it is working

**Comment by Disparity** [comment]
Example here: http://disparity.github.io/pusher-issue/

The tests do not cover this case, because only check for calling, but not that it is passed.

The user does not know anything about the interior decorators who wraps his listeners.
And when you try to unbind - passed the original listener, not a decorator and unbind not occur.

bind decorator: https://github.com/pusher/pusher-angular/blob/master/lib/pusher-angular.js#L168-L171
unbind listener: https://github.com/pusher/pusher-angular/blob/master/lib/pusher-angular.js#L181

**Comment by hamchapman** [comment]
This should be fixed now :+1: 

I've pushed out 0.1.8 as a new version.

Thanks for raising the issue

**Comment by Disparity** [comment]
IMHO not a good idea to return a decorated handler. The user does not need to know the internal implementation, with the decorator.
Then it is better to return a deregistration function for this listener, like a $scope.$on, which is useful for:
```js
var unbindFunction = pusher.bind(event, listener);
$scope.$on('$destroy', unbindFunction));
```
or
```js
var unbindFunction = pusher.bind(event, listener);
unbindFunction();
```
or
```js
$scope.$on('$ destroy', pusher.bind(event, listener)));
```
instead of current implementation:
```js
var decoratedHandler = pusher.bind(event, listener);
$scope.$on('$destroy', function () {
    pusher.unbind(event, decoratedHandler);
}));
```

**Comment by hamchapman** [comment]
I can see the value of the different solutions you've described and they may well be more aligned with Angular conventions. I'm more than happy for you to make a pull request and I'll review it and likely merge it :+1: 

I only went with the solution I went with so that it was differing as little as possible from the pusher-js version.
