### ISSUE TITLE
Question: Dynamically updating the auth headers

### ISSUE THREAD

**Issue by bensquire** [pusher/pusher-angular#18]
Quick question (maybe its silly, I'm not sure). What is the best way to update the Pusher object auth headers after instantiation?

We have SPA which uses bearer tokens to authenticate access to our API. Atm I've managed to update the Pusher object after the user has logged in, using something like:

    pusher.client.config.auth.headers.Authorization = 'Bearer some-sort-of-access-token';

It works, but its pretty hacktastic.

Thanks!
Ben

**Comment by hamchapman** [comment]
Hi Ben, it's definitely a fair question!

Presumably you're instantiating your standard `Pusher` object somewhere and so I think essentially what you're doing at the moment is fine, and the way I'd do it too.

Say you're instantiating it as follows `var client = new Pusher(API_KEY);` then you can then just use `client.config.auth.headers.Authorization` and set that. It looks a bit long, but I think that it's simple enough that it probably doesn't warrant creating a setter in pusher-js.

Feel free to disagree though and I'll get some other opinions :+1:

**Comment by hamchapman** [comment]
Closing for now but feel free to reopen if you still want something different in the library :+1:

**Comment by bensquire** [comment]
@hamchapman Sorry I didn't get back to you RE this. I did continue to use the method described above, my only concern would be if the internal structure ever changed on this (what is essentially) an undocumented property. Either way, thanks to all who have contributed :)

**Comment by JasonKleban** [comment]
yup, can this be made official?  Or what is the right way to upgrade access to additional private channels without reconnecting?

And does `client.config.auth.headers.Authorization = '...'` after connecting _replace_ `new Pusher(pusher_key, { auth: { headers: { pct: '...' } } `?  I'm not clear on that.
