### ISSUE TITLE
What happened to the pusher provider?

### ISSUE THREAD

**Issue by Smolations** [pusher/pusher-angular#19]
The pusher team released [a blog post](https://blog.pusher.com/making-angular-js-realtime-with-pusher/) awhile back showing a demo of how to integrate pusher with angular, and it contained this example:

```javascript
angular.module('myApp', ['doowb.angular-pusher']).

config(['PusherServiceProvider',
  function(PusherServiceProvider) {
    PusherServiceProvider
    .setToken('your_app_key')
    .setOptions({});
  }
]);
```

What happened to this provider? I don't see access to it anywhere in the current pusher-angular code. I think that being able to configure a provider is extremely important so that pusher can be configured for multiple environments. At the moment, we have to inject the app key and configuration in the service that we have defined to work with pusher, which is not ideal.

I would like for your team to consider re-implementing this provider (if it was indeed ever implemented). Thanks for your consideration.  :yum:

**Comment by hamchapman** [comment]
Hi there, the provider was part of a community-created library called [angular-pusher](https://github.com/doowb/angular-pusher). I'm not sure we've got plans to introduce a provider, but if you're keen for it to exist then I'll definitely consider a pull request :+1:
