### ISSUE TITLE
Does it work with pusher-js 4.0 ?

### ISSUE THREAD

**Issue by bartes** [pusher/pusher-angular#23]
Changelog
4.0.0 (2016-12-01)
New major version released due to breaking changes.
[CHANGED] rename bind_all to bind_global
[NEW] unbind_global to remove global bindings
[CHANGED] unbind_all now removes global bindings as well as event specific
[NEW] expose context to pusher level bindings

It looks like bind_all is in use in pusher-angular.

**Comment by hamchapman** [comment]
The `bind_all` and related functions would need to be updated to work with pusher-js 4+

**Comment by anthwinter** [comment]
I have opened a PR to make this work with version 4 - #27

**Comment by hamchapman** [comment]
Merged in #27. This will be part of the 1.0.0 release.
