### ISSUE TITLE
Problems with installing

### ISSUE THREAD

**Issue by Rodeoclash** [pusher/pusher-angular#5]
It seems the heroku endpoint which serves up the library is experiencing 503 errors preventing installation.

[503] https://bower.herokuapp.com/packages/pusher-angular

**Comment by zimbatm** [comment]
Isn't that an issue with bower rather than pusher-angular ?

**Comment by Rodeoclash** [comment]
Ah, correct. It also looks like it's been resolved at bowers end as well.
