### ISSUE TITLE
Alternative CDN

### ISSUE THREAD

**Issue by iurisilvio** [pusher/pusher-angular#6]
jsDeliver CDN is down for me now. It is a local problem, it does not work for one network, but I don't have another CDN to fallback.

As an alternative, I suggest cdnjs.com.

**Comment by hamchapman** [comment]
Good suggestion. I'll take a look at getting it up on cdnjs.com as well

**Comment by jimaek** [comment]
@iurisilvio Hey, jsDelivr seems to be working fine for me and nobody else reports downtime. Do you want to debug the issue with me?

**Comment by iurisilvio** [comment]
@jimaek it was a temporary problem, only in one of my networks (Vivo fiber in Brazil). The other one worked fine.

Something was broken between my internet provider and the Internet. It's already fixed. I'm sure it is not jsdelivr/maxcdn fault, but a redundancy is always good.

**Comment by jimaek** [comment]
I see, thanks for letting me know. If you have issues again ping me on twitter or send me an email. We added a third CDN provider to jsDelivr as well :)
