### ISSUE TITLE
No way to unbind to a Pusher Event

### ISSUE THREAD

**Issue by achintgoel** [pusher/pusher-angular#9]
The Pusher API provides a unbind event, but this library doesnt have that.  Is it possible to add that?  Or is there any workaround?

**Comment by hamchapman** [comment]
I'll take a look at this tomorrow. It should be pretty easy to add I think.

**Comment by danieltheodosius** [comment]
Is there any update on this? I do not think there is any other workaround unless the unbind method is defined in this project.

**Comment by hamchapman** [comment]
Closed by a combination of #10 and f2ef4eff134ce6789e51aebc6a70c2c429c34bc6

**Comment by hamchapman** [comment]
I will push out new versions later today.
